spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpko_community
    username: jpko
    password: jpko1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true