spring:
  application:
    name: jpko-community
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  flyway:
    enabled: true

server:
  port: 8080

jwt:
  access-token-expiration: 3600000      # 1시간 (ms)
  refresh-token-expiration: 604800000   # 7일 (ms)