spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpko_community
    username: jpko
    password: jpko1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
jwt:
  secret: jpko-community-dev-secret-key-must-be-at-least-32bytes