spring:
  application:
    name: jpko-community
  profiles:
    active: dev

server:
  port: 8080

jwt:
  access-token-expiration: 3600000      # 1시간 (ms)
  refresh-token-expiration: 1209600000  # 14일 (ms)