spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/jpko_community
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

cookie:
  secure: true
  same-site: Lax
  domain: ""

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2