-- ============================================================
-- V1: 초기 스키마 (운영 DB baseline)
-- 기존 운영 DB(ddl-auto: update로 생성됨)의 스키마를 그대로 옮긴 baseline.
-- Hibernate 자동 생성 제약조건명은 가독성을 위해 명시적 이름으로 변경함.
-- ============================================================

-- ===================== categories =====================
CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    display_order INTEGER      NOT NULL,
    name          VARCHAR(50)  NOT NULL,
    slug          VARCHAR(50)  NOT NULL,
    CONSTRAINT uk_categories_name UNIQUE (name),
    CONSTRAINT uk_categories_slug UNIQUE (slug)
);

-- ===================== users =====================
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    email      VARCHAR(100),
    nickname   VARCHAR(50)  NOT NULL,
    password   VARCHAR(255),
    role       VARCHAR(20)  NOT NULL,
    status     VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_users_nickname UNIQUE (nickname),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETED'))
);

-- ===================== posts =====================
CREATE TABLE posts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    anonymous   BOOLEAN      NOT NULL,
    content     TEXT         NOT NULL,
    deleted_at  TIMESTAMP(6),
    ip_address  VARCHAR(45),
    title       VARCHAR(100) NOT NULL,
    view_count  INTEGER      NOT NULL,
    category_id BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_posts_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

-- ===================== comments =====================
CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    anonymous  BOOLEAN      NOT NULL,
    content    TEXT         NOT NULL,
    deleted_at TIMESTAMP(6),
    ip_address VARCHAR(45),
    parent_id  BIGINT,
    post_id    BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_id) REFERENCES comments (id)
);

-- ===================== likes =====================
CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    type       VARCHAR(10)  NOT NULL,
    post_id    BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    CONSTRAINT uk_likes_post_user UNIQUE (post_id, user_id),
    CONSTRAINT ck_likes_type CHECK (type IN ('LIKE', 'DISLIKE')),
    CONSTRAINT fk_likes_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ===================== notices =====================
CREATE TABLE notices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    content    TEXT         NOT NULL,
    pinned     BOOLEAN      NOT NULL,
    featured   BOOLEAN      NOT NULL,
    title      VARCHAR(100) NOT NULL,
    view_count INTEGER      NOT NULL,
    user_id    BIGINT       NOT NULL,
    CONSTRAINT fk_notices_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ===================== refresh_tokens =====================
CREATE TABLE refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) NOT NULL,
    device_info VARCHAR(255),
    expires_at  TIMESTAMP(6) NOT NULL,
    ip_address  VARCHAR(45),
    token       VARCHAR(500) NOT NULL,
    user_id     BIGINT       NOT NULL,
    CONSTRAINT uk_refresh_tokens_token UNIQUE (token)
);