-- ============================================================
-- V4: 이메일 인증 여부 컬럼 추가 + 인증/재설정 토큰 테이블 신설
--   email_verified     : 이메일 인증 완료 여부 (비밀번호 재설정 발송 가능 여부 게이트)
--   verification_tokens: 이메일 인증 / 비밀번호 재설정 토큰 저장 (RefreshToken과 동일 판단 기준)
-- ============================================================

-- 1단계: users 테이블에 이메일 인증 여부 컬럼 추가
ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;

-- 2단계: 이메일 인증 / 비밀번호 재설정 토큰 테이블 생성
CREATE TABLE verification_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    user_id    BIGINT       NOT NULL,
    token      VARCHAR(255) NOT NULL,
    type       VARCHAR(20)  NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_verification_tokens_token UNIQUE (token),
    CONSTRAINT ck_verification_tokens_type CHECK (type IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET'))
);